### ISSUE TITLE
Topic Models created with biglda::as_LDA() remain dependent on biglda package

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/biglda#2]
I fitted a mallet LDA topic model and stored it as a `topicmodels` LDA using 

`
topicmodels_lda <- biglda::as_LDA(mallet_lda)
`

and then `saveRDS()` to create an rds file.

When I try to load this rds file, in seems to be required that `biglda` is installed and correctly set up, otherwise this error message occurs:

> Error in .requirePackage(package) : 
  unable to find required package ‘biglda’

My first impression is that this might be a bit of a nuisance in cases in which I just want to use the `topicmodels` or the `topicanalysis` package. Is this behavior deliberate? If so, I would be interested in the underlying rationale.

Edit, just to reiterate: If `biglda` is installed, it seems like the model can be loaded and used as any other model fitted (fit?) with the `topicmodels` package (first impressions, I just used `terms` and `topic` for now). But it is still complaining (although the terms object is created):

> library(topicmodels)
> tm250k <- readRDS("topic_250k.rds")
> xx <- terms(tm250k, 50)
Loading required package: biglda
No mallet installation found. Use mallet_install() for installation!

**Comment by PolMine** [comment]
The nuisance is well understood. A  now apply a somewhat dirty trick to avoid the dependence of the topic model on the biglda package.

The problem to be solved is that the LDA_Gibbs class is not exported by the topicmodels package. So you cannot instantiate an object for this class in another packge (biglda). Instantiating a LDA class object, or a TopicModel class object is not possible either, because these are virtual classes.

To my colution is to duplicate the definition of the LDA_Gibbs class for internal usage in the biglda package.

```r
setClass(
  "LDA_Gibbs",
  representation(
    seedwords = "ANY",
    z = "integer"
  ),
  contains = "LDA",
  prototype(control = new("LDA_Gibbscontrol")
  )
)
```

On this basis, creating a LDA_Gibbs object is possible (`new("LDA_Gibbs")`) within methods of the biglda package. 

Then it needs a dirty hack to avoid that an object you may want to save will rely on the class definition in biglda: You redirect to expectation where to look for the class, like this:

```r
y <- new("LDA_Gibbs")
attr(attr(y, "class"), "package") <- "topicmodels" 
```
As far as I can see, it works.

**Comment by ChristophLeonhardt** [comment]
I would agree: This works as expected. Thanks!

**Comment by ablaette** [comment]
Recently, I introduced classes "LDA_Mallet" and "LDA_Gensim", defined in the package. I think, this is ultimately solved.
